//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TayaIT.Enterprise.EMadbatah.EParlimentService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FNCDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FNCDBEntities object using the connection string found in the 'FNCDBEntities' section of the application configuration file.
        /// </summary>
        public FNCDBEntities() : base("name=FNCDBEntities", "FNCDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FNCDBEntities object.
        /// </summary>
        public FNCDBEntities(string connectionString) : base(connectionString, "FNCDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FNCDBEntities object.
        /// </summary>
        public FNCDBEntities(EntityConnection connection) : base(connection, "FNCDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SessionDiary> SessionDiaries
        {
            get
            {
                if ((_SessionDiaries == null))
                {
                    _SessionDiaries = base.CreateObjectSet<SessionDiary>("SessionDiaries");
                }
                return _SessionDiaries;
            }
        }
        private ObjectSet<SessionDiary> _SessionDiaries;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SessionDiaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessionDiaries(SessionDiary sessionDiary)
        {
            base.AddObject("SessionDiaries", sessionDiary);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FNCDBModel", Name="SessionDiary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SessionDiary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SessionDiary object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static SessionDiary CreateSessionDiary(global::System.Int32 id)
        {
            SessionDiary sessionDiary = new SessionDiary();
            sessionDiary.ID = id;
            return sessionDiary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdatedBy;
        partial void OnUpdatedByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DiaryDate
        {
            get
            {
                return _DiaryDate;
            }
            set
            {
                OnDiaryDateChanging(value);
                ReportPropertyChanging("DiaryDate");
                _DiaryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiaryDate");
                OnDiaryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DiaryDate;
        partial void OnDiaryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDiaryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DiaryNumber
        {
            get
            {
                return _DiaryNumber;
            }
            set
            {
                OnDiaryNumberChanging(value);
                ReportPropertyChanging("DiaryNumber");
                _DiaryNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiaryNumber");
                OnDiaryNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _DiaryNumber;
        partial void OnDiaryNumberChanging(Nullable<global::System.Int32> value);
        partial void OnDiaryNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatorID
        {
            get
            {
                return _CreatorID;
            }
            set
            {
                OnCreatorIDChanging(value);
                ReportPropertyChanging("CreatorID");
                _CreatorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorID");
                OnCreatorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatorID;
        partial void OnCreatorIDChanging(Nullable<global::System.Int32> value);
        partial void OnCreatorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MainItemID
        {
            get
            {
                return _MainItemID;
            }
            set
            {
                OnMainItemIDChanging(value);
                ReportPropertyChanging("MainItemID");
                _MainItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MainItemID");
                OnMainItemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MainItemID;
        partial void OnMainItemIDChanging(Nullable<global::System.Int32> value);
        partial void OnMainItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SubItemID
        {
            get
            {
                return _SubItemID;
            }
            set
            {
                OnSubItemIDChanging(value);
                ReportPropertyChanging("SubItemID");
                _SubItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubItemID");
                OnSubItemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SubItemID;
        partial void OnSubItemIDChanging(Nullable<global::System.Int32> value);
        partial void OnSubItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InterventionOwnerID
        {
            get
            {
                return _InterventionOwnerID;
            }
            set
            {
                OnInterventionOwnerIDChanging(value);
                ReportPropertyChanging("InterventionOwnerID");
                _InterventionOwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterventionOwnerID");
                OnInterventionOwnerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _InterventionOwnerID;
        partial void OnInterventionOwnerIDChanging(Nullable<global::System.Int32> value);
        partial void OnInterventionOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SessionID
        {
            get
            {
                return _SessionID;
            }
            set
            {
                OnSessionIDChanging(value);
                ReportPropertyChanging("SessionID");
                _SessionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SessionID");
                OnSessionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SessionID;
        partial void OnSessionIDChanging(Nullable<global::System.Int32> value);
        partial void OnSessionIDChanged();

        #endregion
    
    }

    #endregion
    
}
