ALTER TABLE [dbo].[SessionAttendant]
    ADD CONSTRAINT [PK_SessionAttendant] PRIMARY KEY CLUSTERED ([SessionID] ASC, [AttendantID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

